@/storage/emulated/0/Android/data/com.tencent.mobileqq/

files/commonlog/tbs/com.tencent.mobileqq/
files/onelog/com_tencent_mobileqq/
files/tbslog/
files/tencent/msflogs/com/tencent/mobileqq/
files/tencent/tbs_live_log/com.tencent.mobileqq/
files/wxa/xlog/

Tencent/MobileQQ/diskcache/

