@com.google.android.inputmethod.latin/Gboard

files/datadownload/shared/public/
files/share_content/contentsuggestion/sticker/
files/hmmoemdata/
files/superpacks/bundled_delight/
files/superpacks/content_cache/
files/superpacks/delight/
files/superpacks/emoji/
files/superpacks/emoticon_content_description/
