@com.microsoft.emmx/Edge

app_chrome/component_crx_cache/
app_chrome/Default/Service Worker/CacheStorage/
app_chrome/Subresource Filter/
app_chrome/PDFReflowGatingFunction/
app_chrome/Safe Browsing/

files/edge_copilot/
files/miniapps/
